// components/aframe/assets.vue
<template>
        <a-assets>
            <defaultAssets />
            <serverAssets />
            <!-- Get list of assets from server and delete default assets -->
        </a-assets>
</template>
<script>
import defaultAssets from './assets-default'
import serverAssets from './assets-server'

export default {
    
}
</script>

// components/xr/scene/assets.tsx
import React from 'react'
import DefaultAssets from './assets-default'
import ServerAssets from './assets-server'

export default class Assets extends React.Component {

  componentDidMount() {
  }

  render() {
    return (
      <a-assets>
        <DefaultAssets />
        <ServerAssets />
      </a-assets>
    )
  }
}
